#!/bin/bash

# Check for Homebrew
if test ! $(which brew); then
  echo "  x Please install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit 1
else
  echo "  + Homebrew found."
fi
