#!/bin/bash -e

if test ! $(which subl); then
  echo "  x You should probably install Sublime Text first:"
  echo "    http://www.sublimetext.com/"
  exit
else
  echo "  + Sublime Text found."
fi

SUBL_PATH=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
SUBL_USER_PATH=$SUBL_PATH/User

if [[ ! -L $SUBL_USER_PATH ]]; then
  echo "  + Link User Settings for Sublime Text"
  if [[ -d $SUBL_USER_PATH ]]; then
    echo "  - Renaming $SUBL_USER_PATH to $SUBL_PATH/User.[timestamp]"
    mv "$SUBL_PATH/User" "$SUBL_PATH/User.$(date +"%Y-%m-%d-%H:%M:%S")"
  fi
  ln -s ~/.dotfiles/sublimetext2/User "$SUBL_PATH/User"
else
  echo "  + User Settings for Sublime Text already linked with .dotfiles"
fi
